spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.132:3306/ajiemall_pms
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.175.132:8848


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000